function graf3(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 29-Sep-2018 16:23:57



% Create axes


% Create plot
plot(X1,Y1);

% Create xlabel
xlabel('Tiempo [s]');

% Create title
title('Convolución','FontSize',14);

% Create ylabel
ylabel('Amplitud');


