
%% interfaz grafica

    f  = figure('units','normalized',...
                'Position',[0 0 1 0.95 ]);
    tgroup = uitabgroup('Parent', f);
    tab1 = uitab('Parent', tgroup, 'Title', 'Calibracion');
    tab2 = uitab('Parent', tgroup, 'Title', 'Greneracion de Sinesweep y Toma de muestras');
    tab3 = uitab('Parent', tgroup, 'Title', 'Procesamiento de Respuestas al impulso');
    
   %% Calibracion con ruido rosa
   axes_1 = axes('Parent',tab1,...
              'Units','normalized','Position',[0.45 0.4 0.4 0.4]);
          text_Titulo_RR = uicontrol('Parent',tab1,...
                'units','normalized',...
               'Style','text',...
               'Fontsize',14,...
               'Position',[0.1 0.85 0.2 0.10 ],...
               'String','Generación de ruido rusa para calibración de la fuente');
          
    text_duracion = uicontrol('Parent',tab1,...
               'units','normalized',...
               'Style','text',...
               'Position',[0.1 0.70 0.2 0.1 ],...
               'String','Duracion de ruido rosa');
     
     edit_DuracionRuido = uicontrol('Parent',tab1,...
                'units','normalized',...
               'Style','edit',...
               'Position',[0.1 0.73 0.2 0.05 ],...
               'String',' ');
           
    text_FsRuido = uicontrol('Parent',tab1,...
                'units','normalized',...
               'Style','text',...
               'Position',[0.11 0.60 0.18 0.1 ],...
               'String','Frecuencia de muestreo');
           
    edit_FdmRuido =    uicontrol('Parent',tab1,...
                'units','normalized',...
               'Style','edit',...
               'Position',[0.1 0.63 0.2 0.05 ],...
               'String',' ');
    
           btnGenerarRuido = uicontrol('Parent',tab1,...
               'units','normalized',...
               'Position',[0.1 0.5 0.2 0.05 ],...
               'style','pushbutton',...
               'String',' Generar ruido rosa ',...
               'Callback',{@rr_gen,edit_DuracionRuido,edit_FdmRuido,axes_1});
           
           btnReproducirRuido = uicontrol('Parent',tab1,...
               'units','normalized',...
               'Position',[0.1 0.4 0.2 0.05 ],...
               'style','pushbutton',...
               'String',' Reproducir Ruido rosa ',...
               'Callback',{@rr_rep});
           
         
        
 %% Generacion sine sweep
 
 
 axes2 = axes('Parent',tab2,...
              'Units','normalized','Position',[0.45 0.4 0.4 0.4]);
          
   bg = uibuttongroup('Parent',tab2,'visible','on','Units','normalized','Position',[0.45 0.85 0.40 0.1],'Title','Seleccione gráfico a visualizar');
        
        r1 = uicontrol('parent',bg,'Style',...
                  'radiobutton',...
                  'String','Sine sweep(t)',...
                  'Units','normalized','Position',[0.1 0.5 0.4 0.25]);
     
        r2 = uicontrol('parent',bg,'Style','radiobutton',...
                  'String','Sine sweep (hz)',...
                 'Units','normalized','Position',[0.3 0.5 0.4 0.25]);

        r3 = uicontrol('parent',bg,'Style','radiobutton',...
                  'String','Filtro inverso (t)',...
                  'Units','normalized','Position',[0.5 0.5 0.4 0.25]);
              
         r4 = uicontrol('parent',bg,'Style','radiobutton',...
                  'String','Filtro inverso (Hz)',...
                  'Units','normalized','Position',[0.7 0.5 0.4 0.25]);
              
         
    text_Titulo_Sine = uicontrol('Parent',tab2,...
                'units','normalized',...
               'Style','text',...
               'Fontsize',14,...
               'Position',[0.1 0.85 0.2 0.10 ],...
               'String','Generación de Sine sweep');
 
 
           
    textf1 = uicontrol('Parent',tab2,...
                'units','normalized',...
               'Style','text',...
               'Position',[0.1 0.78 0.2 0.10 ],...
               'String','Frecuencia inicial');
   edit_Frecuenciainicial =   uicontrol('Parent',tab2,...
                 'units','normalized',...
               'Style','edit',...                                   
               'Position',[0.1 0.8 0.2 0.05 ],...
               'String',''); 
           
   textf2 = uicontrol('Parent',tab2,...
               'units','normalized',...
               'Style','text',...
               'Position',[0.1 0.68 0.2 0.10 ],...
               'String','Frecuencia final');
           
   edit_Frecuenciafinal = uicontrol('Parent',tab2,...
               'units','normalized',...
               'Style','edit',...
               'Position',[0.1 0.7 0.2 0.05 ],...
               'String',''); 
           
    textT = uicontrol('Parent',tab2,...
               'units','normalized',...
               'Style','text',...
               'Position',[0.1 0.63 0.2 0.05 ],...
               'String','Duracion');
           
       edit_Duracion = uicontrol('Parent',tab2,...
                'units','normalized',...
               'Style','edit',...
               'Position',[0.1 0.6 0.2 0.05 ],...
               'String','');
           
        btnGenerarSine = uicontrol('Parent',tab2,...
                'units','normalized',...
               'Position',[0.1 0.5 0.2 0.05 ],...
               'style','pushbutton',...
               'String','Generar sine sweep y filtro inverso',...
               'Callback',{@sn_gen,edit_Frecuenciainicial,edit_Frecuenciafinal,edit_Duracion});
           
           btnReproducir_Sine = uicontrol('Parent',tab2,...
               'units','normalized',...
               'Position',[0.1 0.40 0.2 0.05],...
               'style','pushbutton',...
               'String',' Reproducir Sine sweep ',...
               'Callback',{@sn_rep}); 
           
           btnGraficar = uicontrol('Parent',tab2,...
               'units','normalized',...
               'Position',[0.38 0.87 0.05 0.05],...
               'style','pushbutton',...
               'String',' Graficar ',...
               'Callback',{@graficos,r1,r2,r3,r4,axes2}); 
           
 %% Toma de datos 
 text_TomaDatos = uicontrol('Parent',tab2,...
                'units','normalized',...
               'Style','text',...
               'Fontsize',14,...
               'Position',[0.35 0.2 0.2 0.10 ],...
               'String','Toma de Muestras');
 
 
  text_NumR = uicontrol('Parent',tab2,...
                'units','normalized',...
               'Style','text',...
               'Position',[0.1 0.1 0.2 0.10 ],...
               'String','Numero de Repeticiones');
           
   edit_NumR =  uicontrol('Parent',tab2,...
                 'units','normalized',...
               'Style','edit',...
               'Position',[0.1 0.1 0.2 0.05 ],...
               'String','');
          
    text_Ubic = uicontrol('Parent',tab2,...
                'units','normalized',...
               'Style','text',...
               'Position',[0.4 0.1 0.2 0.10 ],...
               'String','Ubicacion ');
           
   edit_Ubic =    uicontrol('Parent',tab2,...
                 'units','normalized',...
               'Style','edit',...
               'Position',[0.4 0.1 0.2 0.05 ],...
               'String',''); 
           
     btn_toma = uicontrol('Parent',tab2,...
               'units','normalized',...
               'Position',[0.7 0.1 0.2 0.05 ],...
               'style','pushbutton',...
               'String',' Iniciar toma de muestras ',...
               'Callback',{@toma,edit_NumR,edit_Ubic}); 
           
 %% Procesamiento de ir y resultados  
        
  axes3 = axes('Parent',tab3,...
              'Units','normalized','Position',[0.35 0.4 0.4 0.4]);
              
   text_Grafico= uicontrol('Parent',tab3,...
                'units','normalized',...
               'Style','text',...
               'Fontsize',14,...
               'Position',[0.35 0.8 0.4 0.05],...
               'String','Grafico de Filtro en banda de 1 kHz y Curva de Schroeder');
   
           text_IR= uicontrol('Parent',tab3,...
                'units','normalized',...
               'Style','text',...
               'Fontsize',10,...
               'Position',[0.03 0.43 0.15 0.3],...
               'String','Seleccione IR a procesar');       
           
           
        cd Tp2\Formato_wav\
        impulsos = dir('IR');
        cd ..\
        cd ..\
        lista = struct2cell(impulsos);
        lista = lista(1,3:end);
                 
        Lista_IR = uicontrol('Parent',tab3,...
         'units','normalized','Position',[0.03 0.4 0.15 0.3],...
         'style','listbox',...
         'Fontsize',11,...
         'string',lista);
       
       
       bg2 = uibuttongroup('Parent',tab3,'visible','on','Units','normalized',...
       'Position',[0.03 0.28 0.15 0.07],'Title','Seleccione tipo de filtro');
        
        r5 = uicontrol('parent',bg2,'Style',...
                  'radiobutton',...
                  'String','Octava',...
                  'Units','normalized','Position',[0.1 0.5 0.4 0.3]);
     
        r6 = uicontrol('parent',bg2,'Style','radiobutton',...
                  'String','1/3 de Octava',...
                 'Units','normalized','Position',[0.5 0.5 0.4 0.3]);
         
         
           
    tabla_Result = uitable('Parent',tab3,'units','normalized','Position',[0.2 0.1 0.55 0.20],...
    'RowName',{'Frec. Centrales de Banda', 'EDT [s]','TR10 [s]','TR20 [s]','TR30 [s]'},'BackgroundColor',[0.7 0.75 0.8]);    

    btn_Procesar_IR = uicontrol('parent',tab3,'style','pushbutton',...
             'units','normalized',...
               'Position',[0.03 0.20 0.15 0.05 ],...
               'string','Procesar respuesta al impulso',...
               'Callback',{@procesar,r5,r6,Lista_IR,tabla_Result,axes3});
          
     btn_Mostrar_Prom = uicontrol('parent',tab3,'style','pushbutton',...
             'units','normalized',...
               'Position',[0.03 0.13 0.15 0.05 ],...
               'string','Mostrar promedios de las mediciones ',...
               'Callback',{@Mostrar_prom,tabla_Result});
           
%% Funciones locales

function rr_gen(object_handle,event,edit_DuracionRuido,edit_FdmRuido,axes_1)
        try
        t = get(edit_DuracionRuido,'String');
        t = str2num(t);
        Fs = get(edit_FdmRuido,'String');
        Fs = str2num(Fs);
        [p,i] =  pink_noise(t,Fs);
        axes(axes_1);
        graf2 (p,Fs,i,'log');title('Ruido Rosa','FontSize',14);
        catch
            error(['Revise los valores de los campos']);
        end
end
function rr_rep(object_handle,event)
[y,Fs] = audioread('ruido_rosa.wav');
sound (y,Fs);
end
function   sn_gen(object_handle,event,edit_Frecuenciainicial,edit_Frecuenciafinal,edit_Duracion)
   try
    f1 = get(edit_Frecuenciainicial,'String');
    f1 = str2num (f1);
    f2 = get(edit_Frecuenciafinal,'String');
    f2 = str2num (f2);
    T  = get(edit_Duracion,'String');
    T = str2num (T);
    sine_sweep(f1,f2,T);
   catch
      error(['Revise los valores de los campos']);
   end
 end
function  sn_rep(oject_handle,event)
[S,Fs] = audioread('Sweep.wav');
sound (S,Fs);
end
    
function toma(object_handle,event,edit_NumR,edit_Ubic)
    try
    n = get(edit_NumR,'String');
    n = str2num (n);
    u = get(edit_Ubic,'String');
    u = str2num (u);
    toma_datos(n,u);
     catch
      error(['Revise los valores de los campos']);
    end
end

function graficos (object_handle,event,r1,r2,r3,r4,axes2)
      try
        
        [sn.sine , Fs] = audioread('Sweep.wav');
         [sn.inv , Fs] = audioread('Finverso.wav');
          sn.tiempo = 0:1/Fs:(length(sn.sine)/Fs)-1/Fs;
         if r1.Value == 1 
       
            axes(axes2);
            graf1(sn.tiempo,sn.sine);title('Sine-sweep','FontSize',14);
        else if r2.Value == 1
            
            axes(axes2);
            N = numel(sn.sine);
            graf2(sn.sine,44100,N,'log');title('Sine-sweep','FontSize',14);
        else if r3.Value == 1
                
                axes(axes2);
                graf1(sn.tiempo,sn.inv);title('Filtro inverso','FontSize',14);
        else if r4.Value == 1  
                
                axes(axes2);
                N = numel(sn.inv);
            graf2(sn.inv,44100,N,'log');title('Filtro inverso','FontSize',14);
                     
            end
            end
            end
           
    end
      catch
       error(['Primero debe generar']); 
      end
end
function procesar(object_handle,event,r5,r6,Lista_IR,tabla_Result,axes3)
    IR = get(Lista_IR,'String');
    i = get(Lista_IR,'Value');
    IR = IR(i);           
    IR = char(IR);
   
    cd Tp2\
    if r5.Value ==1 
        Banda = 1;
       [MD] = procesar_impulso(IR,Banda);
       tabla_Result.Data = MD.RESULTADOS;
      
      
        save('resultados', '-struct', 'MD');
    else if r6.Value == 1
         Banda = 3;
         [MD] = procesar_impulso(IR,Banda);
         tabla_Result.Data = MD.RESULTADOS;
         save('resultados', '-struct', 'MD');
        end
    end
  cd ..\
    i1K = find(MD.MATRIZFILT(1,:)==1000,1);
      F1K = MD.MATRIZFILT(2:end,i1K);
      tF1k = 0:1/MD.Fs:(length(F1K)-1)/MD.Fs;
      SC1k = MD.SC{i1K};
      tSC1k = 0:1/MD.Fs:(length(SC1k)-1)/MD.Fs;
      F1K = abs(hilbert(F1K));
      F1K = F1K/max(abs(F1K));
      E_F1K = 20*log10(F1K);
      
      axes(axes3);
      plot(tF1k(1:3*MD.Fs),E_F1K(1:3*MD.Fs));hold on
      plot(tSC1k,SC1k);hold off
      xlabel('Tiempo (s)');
      ylabel('Nivel (dB)'); 
      
end

function Mostrar_prom(object_handle,event,tabla_Result);
cd Tp2\
load('Promedio_mediciones_octava.mat');
tabla_Result.Data = Promedio_mediciones_oct;
cd ..\
end

